# Generated by Django 4.2.7 on 2026-02-20 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('zone', models.CharField(default='Zone 1', max_length=50)),
                ('charter_date', models.DateField(blank=True, null=True)),
                ('sponsored_by', models.CharField(blank=True, default='', max_length=200)),
                ('charter_no', models.CharField(blank=True, default='', max_length=50)),
                ('club_id', models.CharField(blank=True, default='', max_length=50)),
                ('logo_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(default='active', max_length=20)),
                ('is_roster_locked', models.BooleanField(default=False)),
                ('district_payment_date', models.DateField(blank=True, null=True)),
                ('officers_json', models.TextField(default='{}')),
                ('members_json', models.TextField(default='[]')),
                ('invoices_json', models.TextField(default='[]')),
                ('metrics_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClubMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_capital', models.CharField(default='0', max_length=50)),
                ('service_hours', models.CharField(default='0', max_length=50)),
                ('lives_touched', models.CharField(default='0', max_length=50)),
                ('rotaracters_in_action', models.CharField(default='0', max_length=50)),
                ('total_points', models.CharField(default='0', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('photo_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type', models.CharField(default='info', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='clubs.club')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ri_id', models.CharField(default='TBD', max_length=50)),
                ('designation', models.CharField(default='Member', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('blood_group', models.CharField(blank=True, default='', max_length=10)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('dues_status', models.CharField(default='Pending', max_length=20)),
                ('district_dues_verified', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_members', to='clubs.club')),
            ],
            options={
                'ordering': ['designation', 'name'],
            },
        ),
    ]
