# Generated by Django 4.2.7 on 2026-02-20 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_auto_20260220_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('meeting_type', models.CharField(choices=[('GBM', 'General Body Meeting'), ('BOD', 'Board Of Directors Meeting')], max_length=3)),
                ('meeting_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('brief_info', models.TextField()),
                ('club_rotaractors', models.IntegerField(default=0)),
                ('visiting_rotaractors', models.IntegerField(default=0)),
                ('rotarians', models.IntegerField(default=0)),
                ('interactors', models.IntegerField(default=0)),
                ('others', models.IntegerField(default=0)),
                ('total_attendance', models.IntegerField(default=0)),
                ('photos_json', models.TextField(default='[]')),
                ('points', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('month', models.CharField(default='January', max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=100)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='clubs.club')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'unique_together': {('club', 'meeting_number', 'month', 'year')},
            },
        ),
    ]
