# Generated by Django 4.2.7 on 2026-02-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_created_at_alter_club_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default='', max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('club_service', 'Club Service Avenue'), ('community_service', 'Community Service Avenue'), ('professional_development', 'Professional Development Avenue'), ('international_service', 'International Service Avenue'), ('sports_wellness', 'Sports and Wellness Avenue'), ('environment', 'Environment Avenue')], max_length=50)),
                ('project_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('project_chair', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('club_rotaractors', models.IntegerField(default=0)),
                ('visiting_rotaractors', models.IntegerField(default=0)),
                ('rotarians', models.IntegerField(default=0)),
                ('interactors', models.IntegerField(default=0)),
                ('others', models.IntegerField(default=0)),
                ('total_attendance', models.IntegerField(default=0)),
                ('additional_points_json', models.TextField(default='[]')),
                ('photos_json', models.TextField(default='[]')),
                ('base_points', models.IntegerField(default=200)),
                ('attendance_points', models.IntegerField(default=0)),
                ('additional_points', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('month', models.CharField(default='January', max_length=20)),
                ('year', models.IntegerField(default=2026)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, default='', max_length=100)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clubs.club')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
