# Generated by Django 4.2.7 on 2026-02-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_community_service_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='general_public_1000_plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='general_public_100_300',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='general_public_500_plus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='general_public_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='mahadhan_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='mahadhan_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('club_service', 'Club Service Avenue'), ('community_service', 'Community Service Avenue'), ('professional_service', 'Professional Service Avenue'), ('professional_development', 'Professional Development Avenue'), ('international_service', 'International Service Avenue'), ('sports_wellness', 'Sports and Wellness Avenue'), ('environment', 'Environment Avenue')], max_length=50),
        ),
    ]
